<a href="https://colab.research.google.com/github/easyhardhoon/deep_learning_frameworks/blob/main/Pytorch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#미분

In [ ]:
import torch
x = torch.ones(2,2, requires_grad = True) #default는 false이다. 이렇게 true로 활성화시켜주면, x 텐서에 대한 기울기를 저장함.
# 딥러닝의 오차역전파법을 자동으로 미분해주는 알고리즘을 위해서이다. (AutoGrad)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [ ]:
y =  x+1
y #겉보기에는 일반 상태와 다를게 없어 보인다.

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [ ]:
z = 2*y**2
res = z.mean() #res가 찐 손실함수의 결과라고 할 수 있다. 각 매개변수에 대한 손실함수의 값이기 때문. 

In [ ]:
res 

tensor(8., grad_fn=<MeanBackward0>)

#위의 과정이
▶변수 선언

▶모델 내 연산 예측값 산출

▶손실함수 계산

▶손실 산출

의 기본 딥러닝구조이다. 이제 이를 토대로


▶ 손실함수에 대한 가중치 매개변수의 기울기 값을 도출한다


In [ ]:
# 이제 우리가 필요한것은
# 손실함수에 대한 매개변수의 기울기 값이다.
# d(res) / d(x_i) = ??
# res  = (z_1 + z_2 + z_3 + z_4) / 4
# z_i = 2 * y_i ** 2
# z_i = 2 * (x_i + 1) ** 2
# 쉽게 : res = (2(x+1)^2)/4 = x제곱 + 2x + 1 의 2분할 = x +1  
# 그래서  d(res) / d(x_i) = x_i + 1 이 된다. (이 과정은 그냥 시험햐볼려고 직접 해본거일 뿐)
res.backward() #연쇄법칙
#z.backward()
x.grad # 각 x_i마다 위의 기울기 값 산출 코드 

tensor([[6., 6.],
        [6., 6.]])

#참고로

z.backward()를 하니

grad can be implicitly created only for scalar outputs 라고 떴다.

res같은 스칼라(상수) 형식 변수에서 backward 함수를 발동시킬 수 있다는 뜻이다..

어찌보면 **손실함수에 대한 가중치 매개변수의 기울기 값**을 구하는 것이니

이 흐름도 당연한 것 같다.

z.backward()가 안되는 명확한 이유는

z가 (2,2) 행렬이기 때문이다

z가 스칼라라면 z.backward가 발동한다.

✅정리하면

    A.backward가 발동되려면 A는 단일상수값, 즉 스칼라값이여야 한다.

    딥러닝 모델의 loss함수 결과값 역시 일련의 선행 값의 평균을 구한 값이기 때문에,

    자연스레 스칼라 값이 도출된다. 이 스칼라 값 형태의 명확한 loss지표 에 대한 

    가중치 매개변수의 기울기 값을 구하는 알고리즘인 것이다.

In [ ]:
##사실은
import torch.nn as nn
import torch.nn.functional as F 
#여기에 모두 선언되어 있고 합성곱 계층 및 복잡한 계층, 활성화함수 등이 모두 저장되어있다.

#자동 미분 복습

In [ ]:
import torch
w = torch.tensor(3.0, requires_grad= True)
y = w**3 + 10
y.backward()
w.grad

tensor(27.)

In [2]:
import torch
import torch.nn as nn

x = torch.ones(5)
y = torch.zeros(3) # 이건 input입니다
w= torch.randn(5,3,requires_grad = True) #가중치 매개변수 초기화입니다
b= torch.randn(3,requires_grad = True) #bias 매개변수 초기화입니다
z= torch.matmul(x,w) + b # 행렬곱 . Affine  계층의 논리입니다
loss_fn = nn.MSELoss() # 손실함수로 nn 라이브러리에 저장되어있는 MSE 손실함수를 사용하겠습니다

loss = loss_fn(z,y) #손실함수를 계산하겠습니다. 결과값은 당연하게도 스칼라입니다. 
loss.backward() #역전파를 구현하겠습니다. 연쇄법으로 자연스레 모든 계층의 미분값이 업데이트 됩니다. 

print(f'loss를 w로 미분한 값 : \n {w.grad}')
print(f'loss를 b로 미분한 값 : \n {b.grad}')


loss를 w로 미분한 값 : 
 tensor([[-0.6813,  2.0534, -1.1082],
        [-0.6813,  2.0534, -1.1082],
        [-0.6813,  2.0534, -1.1082],
        [-0.6813,  2.0534, -1.1082],
        [-0.6813,  2.0534, -1.1082]])
loss를 b로 미분한 값 : 
 tensor([-0.6813,  2.0534, -1.1082])


⚾randn, randint, rand 구별

♟randn(m,n)

    평균이 0이고 표준편차가 1인 가우시안 표준정규분포 난수를 matrix array(m,n)으로 생성한다

    0~1값들 중에서만 뽑아내는 것이 아니라 표준정규분포 중에서 랜덤으로 값을 뽑아내는 거임

♟randint

    시작, n-1 사이의 랜덤숫자 1개 뽑아내기
    
    ex) randint(6) ---> 0~5 사이 랜덤 숫자 1개

    ex) randint(1,20) ----> 1~19 사이 랜덤 숫자 1개

♟rand(m,n)

    0~1의 균일분포 표준정규분포 난수를 matrix array(m,n) 생성. 말그대로 0~1 값 들 중에서 뽑아내는 거임.


⚾Scalar, Vector, Matrix, Tensor 구별

스칼라 : 차원이 없는 값

벡터 : 1차원 값

행렬 : 2차원 값(일반적인 데이터 형태)(batch size, dim)

텐서 : 3차원 값 (batch size, length, dim)

#데이터 불러오기

1. 파이토치 제공 데이터 사용

In [3]:
import torch
import torchvision
import torchvision.transforms as tr
from torch.utils.data import DataLoader, Dataset
import numpy as np

In [4]:
transf = tr.Compose([tr.Resize(8),tr.ToTensor()])
# transforms on PIL Image (PIL 이미지로 변환한다)
# Pad, Grayscale, RandomCrop, Normalize 와 같은 기술들이 compose안에 순서형태로 들어감.
# 예를 들어 위의 경우는 8  by 8 로 resize를 한뒤 tensor 형변환을 함
# 기본적으로 transform에는 PIL image 가 들어가줘야함.
# 아닌 경우 torchvision.transforms.ToPILImage(mode=None)을 해주어야 한다. 


#pytorch의 데이터셋이 지원하는 데이터들은 논문에도 많이 활용되는 고급 데이터셋들입니다.
trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transf) #transform : 데이터 전처리
testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transf)

  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


In [5]:
trainset[0][0].size() #----> 훈련이미지의 각 데이터들의 크기. 즉 하나의 훈련 이미지 데이터의 크기를 말하는 겁니다
#채널 3개에 8 by 8 이미지이다. 
#trainset[100000][0].size()를 해도 되는 것으로 보아 데이터의 개수가 100000을 넘는 것 같다.
# MNIST 때와 마찬가지로 훈련이미지와 정답레이블이 들어가있다고 한다.

torch.Size([3, 8, 8])

In [6]:
trainset[0][1] #----> 0번째 입력 데이터의 정답 레이블
#trainset[0][2] # ---> 는 없다

6

#trainset의 size에 대하여

trainset은 "훈련이미지"와 "정답레이블"로 이루어져 있다.

trainset[0][0],  [1][0] , [2][0]......... 식으로, 각 행에 훈련이미지의 데이터가 하나하나 저장되고

trainset[0][1].  [1][1].  [2][1]..........식으로, 각 행의 다음 칸에 정답 레이블이 하나하나 저장된다


[[trainset]] 

[훈련이미지 데이터]    [정답레이블]

[훈련이미지 데이터]    [정답레이블]

...                       .... 

의 형식입니다

In [7]:
# 배치!!!
trainloader = DataLoader(trainset,batch_size=50,shuffle=True,num_workers=2) # batch size의 크기를 정해주고, shuffle 할지 안할지 선택해주고
# num_workers : dataloading 을 위해 몇개의 서브 프로세스를 사용할 것인가
# 많으면 좋다고 얘기할 수 있을 것지만 서브 프로세스를 너무 많이 써버리면 CPU의 다른 작업에 제약이 생길 수 있음.
testloader = DataLoader(testset, batch_size=50, shuffle=True, num_workers=2)
#이렇게 정한 trainloader, testloader를 인공신경망에 넣기만 하면 끝!!

In [8]:
len(trainloader)
#1000이 의미하는 것 -> 전체 CIFAR10의 train 데이터는 50000개였다. batch_size를 50으로 했기 때문에 1000개의 "배치"가 있다는 뜻이다.

1000

In [9]:
#dataiter의 내용을 확인하고 싶을 때
dataiter = iter(trainloader)
images, labels = dataiter.next() # 이렇게 하나하나 읽어오는 느낌
images.size() # 당연하게도 배치 50으로 묶어놨으니 (50,3,8,8)이 나온다. 데이터 개수(배치 사이즈), 채널 개수, 이미지(입력 데이터) 너비 , 높이 
#[밑바닥 1]의 내용과 다를게 없다. 

torch.Size([50, 3, 8, 8])

# 입력 데이터의 채널 수와 필터의 채널 수는 같아야 한다. 

Pytorch의 [50,3,8,8] 의 의미를 명확히 해야 한다.

순서대로 **[배치 size, 채널 수, 이미지 size(y축), 이미지 size(x축) ]**