<a href="https://colab.research.google.com/github/easyhardhoon/deep_learning_frameworks/blob/main/Pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pytorch 프레임워크 입문

In [ ]:
import torch 
import numpy as np

Pytorch 프레임워크는

import torch 와 같이 단순하게 사용합니다

✅참고 : tensorflow 프레임워크는

import tensorflow as tf 와 같이 사용합니다

In [ ]:
x = torch.empty(5,4)
x
#안의 값들은 그저 쓰레기값 입니다.

tensor([[1.0637e-16, 3.0641e-41, 7.0065e-44, 7.0065e-44],
        [6.3058e-44, 6.7262e-44, 7.0065e-44, 6.3058e-44],
        [6.7262e-44, 7.1466e-44, 1.1771e-43, 6.7262e-44],
        [7.5670e-44, 8.1275e-44, 7.0065e-44, 7.7071e-44],
        [8.1275e-44, 7.2868e-44, 7.8473e-44, 6.4460e-44]])

In [ ]:
type(x)
#torch의 기본 생성 타입은 tensor임을 알 수 있다. 

torch.Tensor

In [ ]:
torch.ones(3,3)
#이렇게 torch는 numpy와 비슷한 역할을 할 수 있습니다.

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#pytorch를 이용하려면 기본 단위를 tensor로 맞추어야한다
l = [13,4]
r = np.array([4,5,6])

In [ ]:
torch.tensor(l)

tensor([13,  4])

In [ ]:
torch.tensor(r)

tensor([4, 5, 6])

In [ ]:
x.size()

torch.Size([5, 4])

In [ ]:
type(x)

torch.Tensor

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.1180, 0.4036],
        [0.2067, 0.0331]])

In [ ]:
torch.add(x,3)

tensor([[3.1180, 3.4036],
        [3.2067, 3.0331]])

In [ ]:
y = torch.rand(2,2)
y

tensor([[0.0760, 0.4069],
        [0.3273, 0.1102]])

In [ ]:
y.add(x)
y

tensor([[0.0760, 0.4069],
        [0.3273, 0.1102]])

In [ ]:
y.add_(x)
y
#add_ 의 의미는, x를 더한 뒤 그 값을 y에 저장하겠다는 의미이다.

tensor([[0.1940, 0.8106],
        [0.5340, 0.1434]])

In [ ]:
y[1,1]
#이렇듯 기본 구성은 tensor라고 해서 특별한 것은 없다.

tensor(0.1434)

In [ ]:
y[:,1]
#1열을 의미한다

tensor([0.8106, 0.1434])

In [ ]:
x = torch.rand(8,8)
x

tensor([[0.1562, 0.9582, 0.5579, 0.6066, 0.1541, 0.4766, 0.5684, 0.5383],
        [0.8020, 0.8769, 0.4333, 0.0552, 0.1455, 0.0548, 0.4477, 0.1463],
        [0.9887, 0.9277, 0.7631, 0.9708, 0.9277, 0.0233, 0.3355, 0.1441],
        [0.3391, 0.0639, 0.9407, 0.9446, 0.9607, 0.2931, 0.7028, 0.3812],
        [0.1370, 0.3132, 0.5495, 0.5329, 0.5457, 0.0438, 0.0843, 0.7896],
        [0.4629, 0.7694, 0.2891, 0.7988, 0.5324, 0.4229, 0.6361, 0.4547],
        [0.7785, 0.9711, 0.5722, 0.6673, 0.1717, 0.9543, 0.5595, 0.1801],
        [0.7179, 0.5831, 0.7584, 0.3916, 0.8461, 0.5561, 0.9872, 0.0930]])

In [ ]:
x.view(64)
#  1*64 로 shape를 바꿀수 있다는 말인듯

tensor([0.1562, 0.9582, 0.5579, 0.6066, 0.1541, 0.4766, 0.5684, 0.5383, 0.8020,
        0.8769, 0.4333, 0.0552, 0.1455, 0.0548, 0.4477, 0.1463, 0.9887, 0.9277,
        0.7631, 0.9708, 0.9277, 0.0233, 0.3355, 0.1441, 0.3391, 0.0639, 0.9407,
        0.9446, 0.9607, 0.2931, 0.7028, 0.3812, 0.1370, 0.3132, 0.5495, 0.5329,
        0.5457, 0.0438, 0.0843, 0.7896, 0.4629, 0.7694, 0.2891, 0.7988, 0.5324,
        0.4229, 0.6361, 0.4547, 0.7785, 0.9711, 0.5722, 0.6673, 0.1717, 0.9543,
        0.5595, 0.1801, 0.7179, 0.5831, 0.7584, 0.3916, 0.8461, 0.5561, 0.9872,
        0.0930])

In [ ]:
x.view(4,16)
# 마찬가지로 4 *16으로 바꿀 수 있다
# 참고로 64를 일일이 16으로 나누기가 힘드니까
x.view(-1,16) #이렇게 나타낼 수 있다. 둘은 같은 말이다. 
# 16은 고정한다는 의미이고 나머지  값은 자동으로 구한다는 개념이다

tensor([[0.1562, 0.9582, 0.5579, 0.6066, 0.1541, 0.4766, 0.5684, 0.5383, 0.8020,
         0.8769, 0.4333, 0.0552, 0.1455, 0.0548, 0.4477, 0.1463],
        [0.9887, 0.9277, 0.7631, 0.9708, 0.9277, 0.0233, 0.3355, 0.1441, 0.3391,
         0.0639, 0.9407, 0.9446, 0.9607, 0.2931, 0.7028, 0.3812],
        [0.1370, 0.3132, 0.5495, 0.5329, 0.5457, 0.0438, 0.0843, 0.7896, 0.4629,
         0.7694, 0.2891, 0.7988, 0.5324, 0.4229, 0.6361, 0.4547],
        [0.7785, 0.9711, 0.5722, 0.6673, 0.1717, 0.9543, 0.5595, 0.1801, 0.7179,
         0.5831, 0.7584, 0.3916, 0.8461, 0.5561, 0.9872, 0.0930]])

In [ ]:
#numpy -> tensor를 배웠으니
#tensor -> numpy 도 해보자
y = x.numpy()
type(y)

numpy.ndarray

In [ ]:
x = torch.ones(1)
x

tensor([1.])

In [ ]:
x.item()
#x안의 값을 뽑아내고 싶다
#오직 x안의 값이 스칼라일 경우( 하나만 있을 경우)만 item으로 값을 뽑아낼수 있다.

1.0

In [ ]:
n = np.array([1,2,3])
n  = torch.tensor(n) #사소한 거지만 n = torch.tensor(n) 이렇게 해주어야 완전히 n의 타입이 변경됩니다
type(n)

torch.Tensor

⏰언제 item()을 사용하는가

    loss함수에서 최종 loss값을 뽑아낼때 사용함. loss는 단일의 스칼라값이기 때문

⏰언제 view()를 사용하는가

    CNN 계층에서 pooling 때 정사각형 모양(input)을 pooling하기 좋게 shape를 바꿀때 편리하게 사용한다